apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todosapi
  name: todosapi
  namespace: todos-ns
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todosapi
status:
  loadBalancer: {}
