apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todosfrontend
  name: todosfrontend
  namespace: front-end-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todosfrontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todosfrontend
    spec:
      containers:
      - image: jackgris/pagination-todos-front-end:0.0.1
        name: todosfrontendk8s
        resources: {}
        env:
          - name: CONFIG_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                key: serverport
                name: front-end-cm
          - name: CONFIG_API_HOST
            valueFrom:
              configMapKeyRef:
                key: apihost
                name: front-end-cm

status: {}
