apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todosfrontend
  name: todosfrontend
  namespace: front-end-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todosfrontend
status:
  loadBalancer: {}
